# Generated by Django 4.1 on 2026-04-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='image',
        ),
    ]
